namespace: flux

bases:
- github.com/fluxcd/flux/deploy

commonLabels:
  app.kubernetes.io/managed-by: kubectl
  app.kubernetes.io/name: fluxcd
  app.kubernetes.io/instance: cluster-flux
  app.kubernetes.io/component: delivery
  app.kubernetes.io/part-of: flux

patchesStrategicMerge:
- patch.dec.yaml

images:
- name: docker.io/fluxcd/flux:1.18.0
  newName: raspbernetes/flux