apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --sync-garbage-collection
            - --manifest-generation=true
            - --memcached-hostname=memcached.flux
            - --memcached-service=
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --git-poll-interval=1m
            - --git-sync-tag=kind
            - --git-branch=master
            - --git-path=clusters/kind/live
            - --git-user="ionfury"
            - --git-email=ionfury@users.noreply.github.com
            - --git-url=git@github.com:ionfury/k8s