version: 1
commandUpdated:
  generators:
    #  Run decrypt files on the /cluster folder and down.
    - command: . /scripts/sops-decrypt-files.sh > /dev/null
    - command: kustomize build .
  patchFile: flux-patch.yaml