apiVersion: ENC[AES256_GCM,data:PsU1xol3Fg==,iv:TGsP6j4T475uDCh3sqbfy+T/viucw2H9NwGZ8mTsyNE=,tag:0evWdF977RGc9kuHh5eIzw==,type:str]
kind: ENC[AES256_GCM,data:l7Q7VFlOFEflEA==,iv:ZeJ70JoJ1j6eJyHgSgipFqNNRk2AzVhG+cuDO5ZloJs=,tag:M/+BjqwpeSI2KTA2o/N+Eg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:h0X+4Xv+RCdPk9R/,iv:6ODFJEHoHbIp51Lfn0zTms3x4lUoHC7A8089mmeSxSw=,tag:cKRfm8AZz4Kp0gAKquIQDg==,type:str]
spec:
    template:
        spec:
            containers:
            -   name: ENC[AES256_GCM,data:LkChB1v65yC3XOiB,iv:iI95MAWt4JFf2Lb5pWrIBj50uRp9jHnOwDRlQTUrKXU=,tag:W7v20wbGmsvSlicAuUbhlw==,type:str]
                env:
                -   name: ENC[AES256_GCM,data:TeOVfgQ=,iv:0n/OazN8lQt3RY4lKZhoy7sbEfTHg1kOhywWJ9+B470=,tag:dn5BiRoljGKhPoaS8kDYzw==,type:str]
                    value: ENC[AES256_GCM,data:dyxScMLntk4ihVQMj1mF7VLLak08JkJ7qZAwcoPpnWn0UAOiAqeJzw9p8E26giQD9ugoeLTY8T+3zUM=,iv:PsAx4/oceCTDx09dhAv2WWZh2RNB+WOrjhTW1zCiyKA=,tag:mkmxdGGi96koT8ULMo8OLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
    -   vault_url: https://sops-d66185f135194728.vault.azure.net
        name: sops-key
        version: 9e093dd599994711b0b52ab0d2baf6e5
        created_at: '2020-03-15T21:09:59Z'
        enc: V-LhZkEfn6_ZRpjmorG6GCLfQ9Q-vGVeHfpFLY1VL02SqFbsN5lVmyto5h5wluMBErwIrvzoS4ZWHRbMr_3jdI-sHYTFip1aOKEBKfAW1a4WTfeIBnuDIr8yAyfAKZgQI-CKd0yP11FA6NyepODP6l1rEcfE2TvNGrbpyYP2Hgs1cjat19YHgW2jfRHX0IGrISestZie8sVOyMhpieWTp38QJWrBboyq5HNWBxn6OEpaVlKJ6IpXbQzf_HQXBN4yC4WBVlUtsARb0DVwN-ljRazZw_X4pTsCB-4BuOHi4NbgxX6bUMynuCYcj0qXUx0JRe2LvSOyRtLLFgtun1uzqg
    lastmodified: '2020-03-15T21:10:00Z'
    mac: ENC[AES256_GCM,data:tXUUR1GwzA/LSqgRcFmlHPgubCOLiQfuzKBFjST+mulp+AdqUXeRbDD4Q6MLt/yCLwOiiJAypOajEykJVDaYCxPYEJZ8RnhqJlLTdZi6OtuEbO/1Von+UsRZkRm2ddqQ+gPzOPlIPXSesFvYxnQLGXSCEpEAjtDgH2ygbH4CB3U=,iv:44ddf+ng9kjp9gxCc0SVpT9A9+1GjOb9vHCOr5iQSr8=,tag:zIO1RGQi4LpgWFsyM5JAuA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
